requires 'perl', '5.006';

requires 'Carton';
requires 'Menlo::Legacy';
requires 'Menlo';
requires 'Menlo::Index::Mirror';
requires 'ExtUtils::Manifest', '1.70';
requires 'ExtUtils::MakeMaker', '7.52';
requires 'Getopt::Long', '2.52';
