requires 'perl', '5.006';
requires "Devel::GlobalDestruction::XS";
requires "Module::Build::Tiny";
requires 'CPAN::Meta::Requirements', '==2.140'; # 2.141 doesn't support perl 5.8.

requires "App::cpm";
requires "Class::C3";
requires "Devel::GlobalDestruction";
requires "ExtUtils::PL2Bat";
requires "MRO::Compat";
requires 'ExtUtils::Manifest', '1.70';
requires 'ExtUtils::MakeMaker', '7.52';
requires 'Getopt::Long', '2.52';
